//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public int User_ID { get; set; }
        public string User_firstName { get; set; }
        public string User_lastName { get; set; }
        public string User_Role { get; set; }
        public string User_Email { get; set; }
        public string User_Password { get; set; }
        public string User_Phone { get; set; }
        public string User_DOB { get; set; }
        public string User_City { get; set; }
        public string User_Gender { get; set; }
        public string User_Address { get; set; }
        public string Is_Deleted { get; set; }
        public string Created_On { get; set; }
        public string Created_By { get; set; }
        public string Modified_On { get; set; }
        public string Modified_By { get; set; }
    }
}
